In [1]:
import pandas as pd
import numpy as np
from cyvcf2 import VCF

In [2]:
###### Read LongTR output on HG002 PacBio #######
calls = []
vcf = VCF(f"/expanse/projects/gymreklab/helia/HipSTR_LR/tests/whole_genome/output/HG002_wg_HiFi_HipSTR_long_chr21.vcf.gz")
for variant in vcf:
    if variant.format('GB')[0] == ".":
        continue
    calls.append([variant.CHROM, variant.POS, variant.INFO['START'], variant.INFO['END'], variant.INFO['PERIOD'],
                  variant.REF, variant.ID, variant.gt_bases[0].split("|"), variant.INFO['DP'],
                  variant.format('GB')[0].split("|")])
PacBio_data = pd.DataFrame(calls, 
    columns = ["chrom","pos", "start", "end", "period", "ref", "ID", "gbs", "dp", 'gb'])

non_homo_21 = PacBio_data[(PacBio_data['chrom'] == 'chr21')]
non_homo_21

,chrom,pos,start,end,period,ref,ID,gbs,dp,gb
0,chr21,5026881,5026881,5026902,6,TTTTGTTTTTGTTTTTGTTTTT,Human_STR_1627987,"[TTTTGTTTTTGTTTTTGTTTTT, TTTTGTTTTGTTTTTGTTTTT]",6,"[0, -1]"
1,chr21,5030765,5030765,5030780,4,TAAATAAATAAATAAA,Human_STR_1627988,"[TAAATAAATAAATAAA, TAAATAAATAAATAAA]",9,"[0, 0]"
2,chr21,5031126,5031126,5031147,1,TTTTTTTTTTTTTTTTTTTTTT,Human_STR_1627989,"[TTTTTTTTTTTTTTTTTTTTTT, TTTTTTTTTTTTTTTTTTTTT]",9,"[0, -1]"
3,chr21,5031738,5031738,5031757,1,AAAAAAAAAGAAAAAAAAAA,Human_STR_1627990,"[AAAAAAAAAGAAAAAAAAAA, AAAAAAAAGAAAAAAAAAA]",9,"[0, -1]"
4,chr21,5039270,5039270,5039298,1,TTTTTCTTTTTCTTTTATTTTTTTTTTTT,Human_STR_1627991,"[TTTTTCTTTTTCTTTTATTTTTTTTTTTT, TTTTTCTTTTTCTT...",13,"[0, 0]"
...,...,...,...,...,...,...,...,...,...,...
20147,chr21,46688832,46688832,46688864,2,ACACACACACACACACACACACACACACACACA,Human_STR_887755,"[ACACACACACACACACACACACACA, ACACACACACACACACAC...",16,"[-8, 6]"
20148,chr21,46689712,46689712,46689732,4,ATTTATTTATTTCTTTATTTA,Human_STR_887756,"[ATTTATTTATTTCTTTATTTA, ATTTATTTATTTCTTTATTTA]",14,"[0, 0]"
20149,chr21,46694502,46694502,46694516,1,TTTTTATTTTTTTTT,Human_STR_887757,"[TTTTTATTTTTTTTT, TTTTTATTTTTTTTTT]",20,"[0, 1]"
20150,chr21,46696282,46696282,46696292,1,TTTTTTTTTTT,Human_STR_887758,"[TTTTTTTTTTT, TTTTTTTTTTTT]",19,"[0, 1]"
20151,chr21,46697535,46697535,46697554,1,AAAAAAAAAAAAAAAAAAAA,Human_STR_887759,"[AAAAAAAAAAAAAAAAAAAA, AAAAAAAAAAAAAAAAAAAAAAA...",19,"[0, 18]"

In [3]:
straglr_pacbio_data = pd.read_csv("output/pacbio_HG002_chr21.bed", sep = "\t")
print(len(straglr_pacbio_data))
PacBio = pd.merge(straglr_pacbio_data, non_homo_21, on = ['start','end'], how = "inner")
PacBio

13705

,#chrom,start,end,repeat_unit,allele1:size,allele1:copy_number,allele1:support,allele2:size,allele2:copy_number,allele2:support,chrom,pos,period,ref,ID,gbs,dp,gb
0,chr21,10001793,10001816,TTTTG,22.7,4.5,65,-,-,-,chr21,10001793,5,TTTTGGTTTGTTTTGTTTTGTTTT,Human_STR_868878,"[TTTTGGTTTGTTTTGTTTTGTTTT, TTTCGGTTTGTTTTGTTTT...",65,"[0, 0]"
1,chr21,10002036,10002050,CCTT,19.0,4.8,63,-,-,-,chr21,10002036,4,CCTTCCTTCCTTCCT,Human_STR_868880,"[CCTTCCTTCCTTCCT, CCTTCCTTCCTTCCT]",64,"[0, 0]"
2,chr21,10003099,10003145,AAAACAA,47.2,6.7,67,-,-,-,chr21,10003099,4,AAACAAACAAACAAACAAACAAAAAACAAACAAACAAACAAAAAACA,Human_STR_868881,[AAACAAACAAACAAACAAACAAAAAACAAACAAACAAACAAAAAA...,69,"[0, 0]"
3,chr21,10003301,10003316,AAAAG,-,-,-,-,-,-,chr21,10003301,1,AAAAGAAAAAAAAAAA,Human_STR_868882,"[AAAAGAAAAAAAAAAA, AAAAGAAAAAAAAAA]",67,"[0, -1]"
4,chr21,10004043,10004056,AAG,8.0,2.7,65,-,-,-,chr21,10004043,1,AAAAAAAAAAAAAA,Human_STR_868883,"[AAAAAAAAAAAAAA, AAAAAAAAAAAA]",69,"[0, -2]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13649,chr21,9989193,9989249,TC,62.7,31.4,89,-,-,-,chr21,9989193,2,TCTCTCTCTCTCTCTCTCTCTCTCTTTCTCTCTCTCTCTGTCTCCC...,Human_STR_868872,[TCTCTCTCTCTCTCTCTCTCTCTTTCTCTCTCTCTCTGTCTCCCT...,89,"[-2, 16]"
13650,chr21,9992425,9992439,CAAA,7.0,1.8,57,-,-,-,chr21,9992425,1,AAAAAAAAAAAAAAA,Human_STR_868873,"[AAAAAAAAAAAAAAA, AAAAAAAAAAAAAAAA]",79,"[0, 1]"
13651,chr21,9992469,9992489,CAAA,24.9,6.2,79,-,-,-,chr21,9992469,4,CAAACAAACAAACAAAAAAAC,Human_STR_868874,"[CAAACAAACAAACAAAAAAAC, CAAACAAACAAACAAAAAAAC]",79,"[0, 0]"
13652,chr21,9995548,9995569,AAAAC,22.0,4.4,69,-,-,-,chr21,9995548,5,AAAAAAAACAAAACAAAACAAA,Human_STR_868876,"[AAAAAAAACAAAACAAAACAAA, AAAAAAAACAAAACAAAACAAA]",69,"[0, 0]"
13653,chr21,9997115,9997131,TTGT,20.1,5.0,37,-,-,-,chr21,9997115,4,TTGTTTGTTTGTTTGTT,Human_STR_1629267,"[TTGTTTGTTTGTTTGTT, TTGTTTGTTTGTTTGTT]",66,"[0, 0]"

In [11]:
def compare(gb_longtr, allele1, allele2, start, end):
    if allele1 == "-":
        return np.nan
    if gb_longtr[0] == ".":
        return np.nan
    start = int(start)
    end = int(end)
    diff = 2
    gb_straglr = []
    gb1 = float(allele1) - (end - start + 1)
    gb2 = "."
    if allele2 != "-":
        gb2 = float(allele2) - (end - start + 1)
    if gb2 != ".":
        gb_straglr = [gb1,gb2]
    else:
        gb_straglr = [gb1,gb1]
    gb_longtr = sorted([int(x) for x in gb_longtr])
    gb_straglr = sorted([int(x) for x in gb_straglr])
    if abs(gb_longtr[0] - gb_straglr[0]) < diff and abs(gb_longtr[1] - gb_straglr[1]) < diff:
        return 1
    if abs(gb_longtr[0] - gb_straglr[0]) < diff or abs(gb_longtr[1] - gb_straglr[1]) < diff:
        return 0.5
    if abs(gb_longtr[0] - gb_straglr[1]) < diff or abs(gb_longtr[0] - gb_straglr[1]) < diff:
        return 0.5
    return 0

PacBio['compare'] = PacBio.apply(lambda row: compare(row['gb'], 
                                                   row['allele1:size'], row['allele2:size'],
                                                    row['start'], row['end']), axis = 1)

In [20]:
PacBio[PacBio['compare'] == 0.5][['repeat_unit', 'allele1:copy_number', 'allele2:copy_number','ref', 'ID','gb']]

,repeat_unit,allele1:copy_number,allele2:copy_number,ref,ID,gb
22,TA,6.6,-,TATATATATATAT,Human_STR_868905,"[0, -2]"
29,AG,8.9,-,GAGAGAGAGAGAGAGAG,Human_STR_868914,"[0, 2]"
33,CTTTTTTT,3.5,-,TTTTTTTTTTTTTTTTTTTTTTTTTTT,Human_STR_868919,"[1, 2]"
36,AAAAAAAAAAAAAAAAGAAAG,2.0,-,AAAAAAAAAAAAAAAAAAAAGAAAAAGAAAAAGAAAAAAGAC,Human_STR_868922,"[0, 1]"
37,TTTTTG,6.5,-,TTTTTGTTTGTTTGTTTGTTTTGTTTTTGTTTTTGTTTTTG,Human_STR_868923,"[0, -4]"
...,...,...,...,...,...,...
13586,TTTC,14.9,-,TTTCTTTTTCCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTT...,Human_STR_1629232,"[4, 12]"
13614,AC,15.0,-,ACACACACACACACACACACACACGCCACACAC,Human_STR_1629265,"[-4, 0]"
13624,ATCT,12.0,-,ATCTATCTATCTATCATCTATCTATCTATCTATCTATCTATCTATC...,Human_STR_868842,"[-15, -19]"
13644,TTATA,3.1,-,TATATTATATATATA,Human_STR_868865,"[0, -2]"
13645,TG,18.4,-,TGTGTGCGTGTATGTGTGTGTGTGTGT,Human_STR_868866,"[0, 8]"

In [19]:
PacBio[PacBio['compare'] == 0.5][['repeat_unit', 'allele1:copy_number','ref', 'ID']]['ref'].iloc[3]

'AAAAAAAAAAAAAAAAAAAAGAAAAAGAAAAAGAAAAAAGAC'